# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
#Import Toggle Button
from py_toggle import PyToggle

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow") 
        MainWindow.setFixedSize(500, 500) #resize
        MainWindow.setStyleSheet("QFrame{\n"
"    background-color: rgb(40, 42, 54);\n"
"}")
        MainWindow.setWindowIcon(QtGui.QIcon('logo1.ico'))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #44475a;\n"
"")     
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.centralwidget.setObjectName("centralwidget")

        #self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        #self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.widget.setStyleSheet("background-color: rgb(68, 71, 90);")
        self.widget.setObjectName("widget")

        self.widget_btn = QtWidgets.QWidget(self.widget)
        self.widget_btn.setGeometry(QtCore.QRect(250, 10, 220, 400))
        self.widget_btn.setStyleSheet("background-color: #363847;\n""border-radius: 10px;\n"
            "border: 3px solid #222;")
        self.widget_btn.setObjectName("widget_btn")
        self.layout_2 = QtWidgets.QVBoxLayout(self.widget_btn)
        self.layout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.layout_2.setContentsMargins(4, 4, 4, 220)
        self.layout_2.setSpacing(20)
        self.layout_2.setObjectName("layout_2")
        self.frame_2 = QtWidgets.QFrame(self.widget_btn)
        self.frame_2.setMaximumSize(QtCore.QSize(180, 162/4))
        self.frame_2.setMinimumSize(QtCore.QSize(180, 162/4))
        self.frame_2.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";"
            "background-color: #363847;\n"
            "border: none;\n"
            )
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2_2 = QtWidgets.QFrame(self.widget_btn)
        self.frame_2_2.setMaximumSize(QtCore.QSize(180, 162/2))
        self.frame_2_2.setMinimumSize(QtCore.QSize(180, 162/2))
        self.frame_2_2.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";"
            "background-color: #363847;\n"
             "border: none;\n"
            )
        self.frame_2_2.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame_2_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2_2.setObjectName("frame_2_2")
        self.layout_2.addWidget(self.frame_2)
        self.layout_2.addWidget(self.frame_2_2)

        
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(45, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        self.pushButton = QtWidgets.QPushButton(self.frame_2_2)
        self.pushButton.setEnabled(True)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ON_OFF.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setGeometry(QtCore.QRect(76, 0, 70, 70))
        self.pushButton.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"    background-color: #bc9df0;\n"
"    border-radius: 35px;\n"
"    padding-top: -3px;\n"
"    padding-right: -2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #c8a7ff;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #ff5555;\n"
"}")    
        self.pushButton.setToolTip("Comenzar Escaneo")
        self.pushButton.setObjectName("pushButton")
        self.toggle = PyToggle(
            width = 50,
            bg_color = "#e5e9ff",
            circle_color = "#44475a",
            active_color = "#c1a1e8")
        #self.toggle.setGeometry(QtCore.QRect(260, 70, 160, 160))
        self.toggle.setObjectName("toggle")
        #self.toggle.active_color = "#8be9fd"
        self.Conexion = QtWidgets.QLabel(self.frame_2)
        self.Conexion.setMinimumSize(QtCore.QSize(70, 30))
        self.Conexion.setMaximumSize(QtCore.QSize(70, 30))     
        self.Conexion.setStyleSheet("color:#ff79c6;\n"
"")
        self.Conexion.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Conexion.setObjectName("Conexion")
       # self.widget_toggle = QtWidgets.QWidget(self.widget)
       # self.widget_toggle.setGeometry(QtCore.QRect(290+101/2-40, 130-70, 80, 40))
       # self.widget_toggle.setObjectName("widget_toggle")
       # self.layout_toggle = QtWidgets.QVBoxLayout(self.widget_toggle)
       # self.layout_toggle.addWidget(self.toggle)

        self.horizontalLayout_2.addWidget(self.Conexion)
        self.horizontalLayout_2.addWidget(self.toggle)
        # self.horizontalScrollBar = QtWidgets.QScrollBar(self.widget)
        # self.horizontalScrollBar.setGeometry(QtCore.QRect(260, 70, 160, 16))
        # self.horizontalScrollBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        # self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(6, 10, 235, 170))
        self.widget1.setObjectName("widget1")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.frame = QtWidgets.QFrame(self.widget1)
        self.frame.setMaximumSize(QtCore.QSize(235, 170))
        self.frame.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
            "background-color: #363847;\n"
            "border-radius: 15px;\n"
            "border: 3px solid #222;\n")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        
        self.Edit_Alto = QtWidgets.QLineEdit(self.frame)
        self.Edit_Alto.setMaximumSize(QtCore.QSize(90, 25))
        self.Edit_Alto.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Edit_Alto.setTextMargins(10,0,0,0)
        self.Edit_Alto.setPlaceholderText("mm")
        self.Edit_Alto.setClearButtonEnabled(True)
        self.Edit_Alto.setObjectName("Edit_Alto")

        self.Edit_Ancho = QtWidgets.QLineEdit(self.frame)
        self.Edit_Ancho.setMaximumSize(QtCore.QSize(90, 25))
        self.Edit_Ancho.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Edit_Ancho.setTextMargins(10,0,0,0)
        self.Edit_Ancho.setPlaceholderText("mm")
        self.Edit_Ancho.setClearButtonEnabled(True)
        self.Edit_Ancho.setObjectName("Edit_Ancho")

        self.gridLayout.addWidget(self.Edit_Alto, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.Edit_Ancho, 2, 2, 1, 1)
        
        self.Alto = QtWidgets.QLabel(self.frame)
        self.Alto.setMaximumSize(QtCore.QSize(100, 30))
        self.Alto.setStyleSheet("color:#ff79c6;\n"
            "border: none;\n"
        )
        self.Alto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Alto.setObjectName("Alto")
        self.gridLayout.addWidget(self.Alto, 0, 0, 1, 1)
        self.Ancho = QtWidgets.QLabel(self.frame)
        self.Ancho.setMaximumSize(QtCore.QSize(100, 30))
        self.Ancho.setStyleSheet("border: none;\n""color:#ff79c6;")
        self.Ancho.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Ancho.setObjectName("Ancho")
        self.gridLayout.addWidget(self.Ancho, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        
        self.Resolucion = QtWidgets.QLabel(self.frame)
        self.Resolucion.setMaximumSize(QtCore.QSize(100, 30))
        self.Resolucion.setStyleSheet("border: none;\n""color:#ff79c6;")
        self.Resolucion.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Resolucion.setObjectName("Resolucion")
        self.gridLayout.addWidget(self.Resolucion,4,0,1,1)
        self.Resolucion_Edit = QtWidgets.QLineEdit(self.frame)
        self.Resolucion_Edit.setMaximumSize(QtCore.QSize(90, 25))
        self.Resolucion_Edit.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Resolucion_Edit.setTextMargins(10,0,0,0)
        self.Resolucion_Edit.setPlaceholderText("µm")
        self.Resolucion_Edit.setClearButtonEnabled(True)
        self.Resolucion_Edit.setObjectName("Resolucion_Edit")
        self.gridLayout.addWidget(self.Resolucion_Edit,4,2,1,1)
        #self.horizontalLayout.addWidget(self.Resolucion_Edit)
        #self.verticalLayout_2.addWidget(self.widget)
        

        self.widget_cam = QtWidgets.QWidget(self.widget)
        self.widget_cam.setGeometry(QtCore.QRect(10, 180, 230, 250))
        self.widget_cam.setObjectName("widget_cam")

        self.verticalLayout_cam = QtWidgets.QVBoxLayout(self.widget_cam)
        self.verticalLayout_cam.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_cam.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_cam.setSpacing(0)
        self.verticalLayout_cam.setObjectName("verticalLayout_cam")

        self.frame_cam = QtWidgets.QFrame(self.widget_cam)
        self.frame_cam.setMaximumSize(QtCore.QSize(230, 230))
        self.frame_cam.setMinimumSize(QtCore.QSize(230, 230))
        self.frame_cam.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
            "background-color: #363847;\n"
            "border-radius: 15px;\n"
            "border: 3px solid #222;\n")
        self.frame_cam.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame_cam.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cam.setObjectName("frame_cam")

        self.gridLayout_cam = QtWidgets.QGridLayout(self.frame_cam)
        self.gridLayout_cam.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_cam.setHorizontalSpacing(0)
        self.gridLayout_cam.setVerticalSpacing(0)
        self.gridLayout_cam.setObjectName("gridLayout")
        #spacerItem = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        #self.gridLayout_cam.addItem(spacerItem, 1, 1, 1, 1)

        self.preview_cam = QtWidgets.QPushButton(self.frame_cam)
        self.preview_cam.setEnabled(True)
        self.preview_cam.setCheckable(True)
        self.preview_cam.setChecked(False)
        self.preview_cam.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        preview_icon = QtGui.QIcon()
        preview_icon.addPixmap(QtGui.QPixmap("cam_ico.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.preview_cam.setIcon(preview_icon)
        self.preview_cam.setIconSize(QtCore.QSize(35, 35))
        #self.preview_cam.setGeometry(QtCore.QRect(76, 0, 70, 70))
        self.preview_cam.setMinimumSize(QtCore.QSize(78, 52))
        self.preview_cam.setMaximumSize(QtCore.QSize(78, 52))
        self.preview_cam.setStyleSheet("QPushButton{\n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"    background-color: #bc9df0;\n"
"    border-radius: 26px;\n"
"    padding-top: -3px;\n"
"    padding-right: -2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #c8a7ff;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #ff5555;\n"
"}")    
        #self.preview_cam.setText("Preview")
        self.preview_cam.setToolTip("Abrir una preview\nde la cámara")
        self.preview_cam.setObjectName("preview_cam")

        self.tomar_foto = QtWidgets.QPushButton(self.frame_cam)
        self.tomar_foto.setEnabled(True)
        self.tomar_foto.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("../../../Documents/Microscopio_Confocal/Microscopio_Confocal_V1.0/ON_OFF.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        #self.preview_cam.setIcon(icon)
        #self.tomar_foto.setIconSize(QtCore.QSize(50, 50))
        #self.tomar_foto.setGeometry(QtCore.QRect(76, 0, 70, 70))
        self.tomar_foto.setMinimumSize(QtCore.QSize(90, 52))
        self.tomar_foto.setMaximumSize(QtCore.QSize(90, 52))
        self.tomar_foto.setStyleSheet("QPushButton{\n"
"    font: 63 13pt \"Bahnschrift SemiBold\";\n"
"color:#fff;\n"
"    background-color: #bc9df0;\n"
"    border-radius: 26px;\n"
"    padding-top: -3px;\n"
"    padding-right: -2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #c8a7ff;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #bc9df0;\n"
"    border-bottom: 5px solid #222;\n"
"    border-left: 4px solid #222;\n"
"    border-right: 4px solid #222;\n"
"    border-top: 4px solid #222;\n"
"    padding-top: -6px;\n"
"    padding-right: -2px;\n"
"}")    
        self.tomar_foto.setText("Hacer\nFoto")
        self.tomar_foto.setToolTip("tomar una instantánea")
        self.tomar_foto.setObjectName("tomar_foto")

        self.change_ROI = QtWidgets.QPushButton(self.frame_cam)
        self.change_ROI.setEnabled(True)
        self.change_ROI.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("../../../Documents/Microscopio_Confocal/Microscopio_Confocal_V1.0/ON_OFF.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        #self.preview_cam.setIcon(icon)
        #self.change_ROI.setIconSize(QtCore.QSize(50, 50))
        #self.tomar_foto.setGeometry(QtCore.QRect(76, 0, 70, 70))
        self.change_ROI.setMinimumSize(QtCore.QSize(78, 48))
        self.change_ROI.setMaximumSize(QtCore.QSize(78, 48))
        self.change_ROI.setStyleSheet("QPushButton{\n"
"    font: 60 11pt \"Bahnschrift SemiBold\";\n"
"color:#fff;\n"
"    background-color: #bc9df0;\n"
"    border-radius: 23px;\n"
"    padding-top: -3px;\n"
"    padding-right: -2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #c8a7ff;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #bc9df0;\n"
"    border-bottom: 5px solid #222;\n"
"    border-left: 4px solid #222;\n"
"    border-right: 4px solid #222;\n"
"    border-top: 4px solid #222;\n"
"    padding-top: -6px;\n"
"    padding-right: -2px;\n"
"}")    
        self.change_ROI.setText("Cambiar\nROI")
        self.change_ROI.setToolTip("Cambiar la \nregión de interes")
        self.change_ROI.setObjectName("change_ROI")

        SUP = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉")

        self.Edit_x1 = QtWidgets.QLineEdit(self.frame_cam)
        self.Edit_x1.setMaximumSize(QtCore.QSize(90, 25))
        self.Edit_x1.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Edit_x1.setTextMargins(10,0,0,0)
        self.Edit_x1.setPlaceholderText("X1".translate(SUP))
        self.Edit_x1.setObjectName("Edit_x1")

        self.Edit_y1 = QtWidgets.QLineEdit(self.frame_cam)
        self.Edit_y1.setMaximumSize(QtCore.QSize(90, 25))
        self.Edit_y1.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Edit_y1.setTextMargins(10,0,0,0)
        self.Edit_y1.setPlaceholderText("Y1".translate(SUP))
        self.Edit_y1.setObjectName("Edit_y1")

        self.Edit_x2 = QtWidgets.QLineEdit(self.frame_cam)
        self.Edit_x2.setMaximumSize(QtCore.QSize(90, 25))
        self.Edit_x2.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Edit_x2.setTextMargins(10,0,0,0)
        self.Edit_x2.setPlaceholderText("X2".translate(SUP))
        self.Edit_x2.setObjectName("Edit_x2")

        self.Edit_y2 = QtWidgets.QLineEdit(self.frame_cam)
        self.Edit_y2.setMaximumSize(QtCore.QSize(90, 25))
        self.Edit_y2.setStyleSheet("border-radius: 10px;\n"
            "border: none;\n"
            "background-color: #e5e9ff;")
        self.Edit_y2.setTextMargins(10,0,0,0)
        self.Edit_y2.setPlaceholderText("Y2".translate(SUP))
        self.Edit_y2.setObjectName("Edit_y2")
    
        self.ROI = QtWidgets.QLabel(self.frame_cam)
        self.ROI.setMaximumSize(QtCore.QSize(40, 20))
        self.ROI.setStyleSheet("border: none;\n""color:#ff79c6;")
        self.ROI.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ROI.setObjectName("ROI")

        self.gridLayout_cam.addWidget(self.preview_cam, 0, 0, 1, 1)
        self.gridLayout_cam.addWidget(self.tomar_foto, 0, 1, 1, 1)
        self.gridLayout_cam.addWidget(self.Edit_x1, 2, 0, 1, 1)
        self.gridLayout_cam.addWidget(self.Edit_y1, 2, 1, 1, 1)
        self.gridLayout_cam.addWidget(self.Edit_x2, 3, 0, 1, 1)
        self.gridLayout_cam.addWidget(self.Edit_y2, 3, 1, 1, 1)
        self.gridLayout_cam.addWidget(self.ROI, 1, 0, 1, 1)
        self.gridLayout_cam.addWidget(self.change_ROI, 4, 0, 1, 1)


        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Microscopio Confocal"))
        #self.pushButton.setText(_translate("MainWindow", "Escanear"))
        self.Alto.setText(_translate("MainWindow", "Alto:"))
        self.Ancho.setText(_translate("MainWindow", "Ancho:"))
        self.Resolucion.setText(_translate("MainWindow", "Resolución:"))
        self.ROI.setText(_translate("MainWindow", "ROI:"))
        self.Conexion.setText(_translate("MainWindow", "Arduino:"))

    #def changeColor(self, active_color = "#2222"):
    #   self.toggle.changeProperties(active_color)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
